/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ca-central-1",
    "aws_cognito_identity_pool_id": "ca-central-1:68252d33-661c-4d0a-9c8b-72237ec7f876",
    "aws_cognito_region": "ca-central-1",
    "aws_user_pools_id": "ca-central-1_EHnR4lzII",
    "aws_user_pools_web_client_id": "4m6r5t9kgjforta065705d75g0",
    "oauth": {}
};


export default awsmobile;
